### ISSUE TITLE
ช่องค้นหาจำค่าเดิม

### ISSUE THREAD

**Issue by nobutsta** [earthchie/jquery.Thailand.js#10]
มีประเด็นมารบกวนอีกเรื่องนึงครับ คือเมื่อทำการค้นหาครั้งแรกไปแล้วแต่ยังไม่เปลี่ยนหน้า พอคลิกที่ช่องค้นหาอีกครั้ง โปรแกรมจะลิสต์รายการค้นหาล่าสุดลงมาเป็นดร็อปดาวน์อีกครั้งหนึ่งครับ จะต้องทำยังไงไม่ให้มันค้นหาซ้ำ/ให้เหมือนกับการรีเฟรช

**Comment by earthchie** [comment]
เป็นปัญหาจากทาง typeahead.js มา เดี๋ยวผมจะลองหาวิธี workaround ให้ครับ

**Comment by nobutsta** [comment]
ขอบคุณครับผม/เดี๋ยวช่วยหาบักเพิ่มให้นะครับ จะได้เพอร์เฟค :D

**Comment by earthchie** [comment]
แก้ไขในเวอร์ชัน 1.3.7 แล้ว ขอบคุณครับ
https://github.com/earthchie/jquery.Thailand.js/commit/7801222ec570cd742cda77b0f19b51a5829a9497
