### ISSUE TITLE
Multi input

### ISSUE THREAD

**Issue by nobutsta** [earthchie/jquery.Thailand.js#12]
มีเรื่องมารบกวนอีกรอบครับ, ผมมีฟอร์มที่ต้องการใส่ที่อยู่สองครั้ง ครั้งแรกเป็นที่อยู่ตามบัตร ปชช. อีกอันเป็นที่อยู่ร้าน มีวิธีไหนที่ผมไม่ต้องสร้างไอดีสองครั้งมั้ยครับ?

**Comment by earthchie** [comment]
ไม่มีครับ มีสองอันก็ต้องแยกกันสองอัน
