### ISSUE TITLE
เคลียร์ผลการค้นหาก่อนแสดงผลใหม่

### ISSUE THREAD

**Issue by nobutsta** [earthchie/jquery.Thailand.js#13]
สวัสดีครับ,
รบกวนอีกครั้ง ผมอยากให้ลบผลการค้นหาอันเก่า ก่อนที่จะมีการใส่ผลอันใหม่ลงใน #search ผมลองใช้ $('#search').html(''); แล้วก็ไม่เวิร์ค ไม่ทราบต้องทำยังไงครับ?

![image](https://cloud.githubusercontent.com/assets/1971066/25660110/fae4445c-3034-11e7-965f-fcf6aa3f844e.png)

**Comment by nobutsta** [comment]
ได้แล้วครับ  $('#search_result').empty().prepend('');

**Comment by earthchie** [comment]
จริงๆ เขียนแบบนี้เหมาะกว่าครับ

```
$('#search_result').html('');
```

ถ้าจะให้เคลียร์ตอน focus ก็เขียนแบบนี้

```
$('#search').focus(function(){
   $('#search_result').html('');
});
```
