### ISSUE TITLE
บางอันไม่มีรหัสไปรษณีย์

### ISSUE THREAD

**Issue by nobutsta** [earthchie/jquery.Thailand.js#14]
ผมลองใส่คีย์เวิร์ดด้วยคำว่า "เกาะ" ซึ่งบางแห่งมันอยู่ในอำเภอเมืองแต่กลับไม่มีรหัสไปรษณีย์ครับ

![image](https://cloud.githubusercontent.com/assets/1971066/25660291/c873afde-3035-11e7-877d-42c1a5a46b05.png)

**Comment by earthchie** [comment]
เพราะเค้าไม่มีรหัสไปรษณีย์อยู่แล้วครับ
