### ISSUE TITLE
Bug in Safari [SyntaxError: Unexpected keyword 'const']

### ISSUE THREAD

**Issue by PsKs** [earthchie/jquery.Thailand.js#16]
สวัสดีครับ พอดีลองเล่น demo แล้ว Safari ฟ้อง error ของ JQL.js ครับ

JQL.min.js:8 [SyntaxError: Unexpected keyword 'const']

Safari v9.1.3

**Comment by earthchie** [comment]
บน device ไหนครับ 

สงสัยจะยังไม่รู้จัก es6 เดี๋ยวว่างๆ downgrade ให้ครับ

**Comment by PsKs** [comment]
อ่อลืมครับ OSX 10.9.5 ครับ

**Comment by earthchie** [comment]
รับแซ่บ

**Comment by earthchie** [comment]
แก้ไขใน https://github.com/earthchie/jquery.Thailand.js/commit/62cd63753fa9ee1d7811e3a9ee3beb45c3753abb แล้วครับ 

อย่างไรก็ตามผมแนะนำให้อัพเดต Safari เป็นเวอร์ชันใหม่ล่าสุดดีกว่าครับ

**Comment by PsKs** [comment]
ขอบคุณมากนะครับ ถ้าพบ bug จะแจ้งให้ทราบครับ

ps. ยังไม่อยากอัพ osx ตอนนี้อ่าครัช ฮา
