### ISSUE TITLE
Install in Bower or NPM?

### ISSUE THREAD

**Issue by zorosun** [earthchie/jquery.Thailand.js#17]
This is a great project so I think it will benefit more people if this package is pushed to NPM or Bower. What do you guys think? 

PS. This project saved me so much time! thx

**Comment by earthchie** [comment]
ช่วงนี้งานผมเยอะมากๆ เลย ถ้าสะดวกแล้ว จะมาดำเนินการให้นะครับ
ระหว่างนี้ถ้าใครสะดวก นำขึ้นให้เลยก็ยินดีครับ license ผมเปิดเต็มที่ครับ

**Comment by earthchie** [comment]
Sellsuki fork ไปแล้วครับ :)

https://github.com/Sellsuki/thai-address-database

**Comment by zorosun** [comment]
ขอบคุณครับ
