### ISSUE TITLE
ฟังก์ชั่นไม่ทำงาน เมื่อใช้ร่วมกับ bootstrapValidator

### ISSUE THREAD

**Issue by worawitinter** [earthchie/jquery.Thailand.js#19]
ขอบคุณสำหรับการแบ่งปันนะครับ

ผมลองโหลดมาติดตั้งแล้ว แต่พบว่าฟังก์ชั่นไม่สามารถทำงานได้ ไม่ทราบว่าผมต้องประกาศหรือเพิ่มเติมอะไรอีกบ้างครับ

function bootstrapValidator
![capture](https://user-images.githubusercontent.com/1763383/30238231-b12fdb72-9575-11e7-8014-14d44627e468.JPG)

เรียกใช้งาน jquery.Thailand.js
![pic](https://user-images.githubusercontent.com/1763383/30238228-9c6fe4fc-9575-11e7-80f6-e9692a34f3f6.JPG)

**Comment by earthchie** [comment]
อ่าว close ไปซะแล้ว แก้ไขได้แล้วใช่ไหมครับ

**Comment by worawitinter** [comment]
ผมจะลอง debug ดูอีกรอบครับ มันจะใช้งานก็ต่อเมื่อผมไป edit record ที่บันทึกไว้ก่อนหน้าไว้แล้ว แล้วพอสร้างฟอร์มใหม่ ก็จะใช้ไม่ได้แล้ว เพราะผมเรียกให้งานผ่าน modal form เดียวกัน แค่ส่งผ่าน form mode new/edit เดี๋ยวยังไงจะมารายงานปัญหาอีกรอบครับ

ผมสามารถสร้างเป็นฟังก์ชั่นได้มั้ยครับ บาง browser มันชอบฟ้องว่า script in not in function หากเราใส่ไว้ในฟังก์ชันแล้วค่อยไปเรียก event onkeypress หรืออะไรก็ตามแต่  เพราะเคยลองทำแล้ว พอพิมพ์ไปแค่ตัวอักษรแรกฟังก์ชั้นก็หยุดไปเลย ขอบคุณลวงหน้านะครับ

**Comment by worawitinter** [comment]
ผมลอง debug แล้ว สรุปเป็น bug จากตัว plugin bootstrapvalidator ของมันเอง ตอนนี้ใช้ได้เหมือนเดิมโดยไม่มีปัญหาหลังจาก fixed
