### ISSUE TITLE
ใช้กับ angular ได้ไหมครับ

### ISSUE THREAD

**Issue by Thainainan03** [earthchie/jquery.Thailand.js#20]

**Comment by earthchie** [comment]
ตามหลักควรใช้ได้ครับ แต่ยังไม่ได้เทส

**Comment by Thainainan03** [comment]
$.(Thailand) นี้คืออะไรครับ แล้วเอาไปใช้ยังไงครับ ใช้กับ jquery ใช่ไหมครับ 
![image](https://user-images.githubusercontent.com/26254784/32472237-38917d2c-c394-11e7-9031-1444431f7aed.png)

**Comment by earthchie** [comment]
เขียนโค้ดผิดนะครับ ต้องเป็น ``$.Thailand()``
แล้วก็ มันเป็น jquery plugins ก็ต้องใช้กับ jquery ได้แน่นอนอยู่แล้ว
