### ISSUE TITLE
Cannot set value of textbox after searching with ลองกรอกอย่างใดอย่างหนึ่ง ตำบล, อำเภอ, จังหวัด หรือ รหัสไปรษณีย์

### ISSUE THREAD

**Issue by toanthree** [earthchie/jquery.Thailand.js#22]
Hi, 
I have used this library, it is great. I want to ask can we remain the data in the search box after searching.

Image description link : http://prntscr.com/hir7bg

**Comment by earthchie** [comment]
Hello toanthree,

Thanks for using this lib, I really surprise to see a foreigner here.

Alright answer your question: No, you cannot do that in this current version. However you can change the code yourself very easily.

From [jquery.Thailand.js Line #299](https://github.com/earthchie/jquery.Thailand.js/blob/master/jquery.Thailand.js/src/jquery.Thailand.js#L299)

replace this line
```
return '';
```

with this 
```
return options.$search.val();
```

This should do the trick.

**Comment by toanthree** [comment]
That is not what i want, i want the suggestion autocomplete result remainning after clicking on it.

If the library can support this part, that would be great.

Thanks for your answer.

**Comment by earthchie** [comment]
you're welcome
