### ISSUE TITLE
Update ฐานข้อมูล

### ISSUE THREAD

**Issue by n9ti** [earthchie/jquery.Thailand.js#23]
ถ้าผมต้องการจะช่วย Update ฐานข้อมูล จะต้องทำอย่างไรบ้างครับ
คือเห็นว่ามีโฟลเดอร์ raw_database และ tools  อยู่แต่ไม่รู้ว่าจะต้องทำอย่างไรบ้างถึงจะ Update ตัว db.json ได้ครับ

**Comment by earthchie** [comment]
พิมพ์แจ้งตรงนี้ได้เลยครับ เดี๋ยวผมนำไปอัพเดตให้

**Comment by noomerzx** [comment]
ในเบสเป็น 22220 ครับ จันทบุรี
22160 | แก่งหางแมว | แก่งหางแมว | จันทบุรี |  
22160 | ขุนซ่อง | แก่งหางแมว | จันทบุรี |  
22160 | เขาวงกต | แก่งหางแมว | จันทบุรี |  
22160 | พวา | แก่งหางแมว | จันทบุรี |  
22160 | สามพี่น้อง | แก่งหางแมว | จันทบุรี
*****************
- ต.ประดาง, ต.เชียงทอง ,ต.นาโบสถ์ 
อ.วังเจ้า จ.ตาก 
เปลี่ยนรหัสไปรษณีย์เป็น 63180
*****************
-ต.บางเสาธง ,ต.ศรีษะจรเข้น้อย ,ต.ศรีษะจรเข้ใหญ่ 
อ.บางเสาธง จ.สมุทรปราการ 
เปลี่ยนรหัสไปรษณีย์เป็น 10570
*****************

ไม่แน่ใจว่าพอจะมีวิธีอัปเดต raw database แล้วสั่ง build ออกมาเป็น geodb.json และ db.json ได้น่าจะเวิคครับผม หรือมีวิธีไหนบ้างที่จะสามารถอัปเดตเองได้อ่าคร๊าบ แบบที่ไม่ต้องแก้ที่ db, geodb เองทีละอัน

ขอบคุณครับ

**Comment by earthchie** [comment]
ใน repo มี tools อยู่แต่ผมใช้ไม่เป็นเหมือนกันยังไม่ได้ลอง เป็นของท่านอื่นส่ง pr มา แต่ดูคร่าวๆ แล้วใช้ไม่ยากนะครับ เป็น nodejs สั่งรันได้เลย

เดี๋ยวแก้ไขแล้วจะแจ้งให้ทราบนะครับ

**Comment by noomerzx** [comment]
แจ้งเพิ่มเติมครับ เช็คกับไปรษณีแล้ว

จังหวัด สงขลา ต.ท่าแฝก อ.ท่าปลา ได้ถูกย้ายมาอยู่กับ ต.ท่าแฝก อ.น้ำปาด

**Comment by earthchie** [comment]
เอางี้ เดี๋ยวเสาร์อาทิตย์นี้ผมเขียนตัวแปลงออนไลน์ให้เลยครับ กด browse และ download เป็นอันจบ

**Comment by noomerzx** [comment]
มี link ต้นฉบับมั้ยครับ พอดีลองแกะไฟล์ Tools ดูละแต่มันอ่าน data.json ซึ่งไม่รู้ว่าหน้าตามันเป็นยังไง เผื่อจะลองทำ converter จาก excel raw db มาเป็น input ให้ Tool มันแปลงมาเป็น db/geodb

**Comment by earthchie** [comment]
เอาทีละประเด็น 

ฐานข้อมูลหลักเลย ผมเอามาจากไปรษณีย์ไทย ซึ่งก็คือไฟล์ excel นั่นแหละครับ ซึ่งสังเกตได้ว่า ไม่มีรหัสพื้นที่...

รหัสพื้นที่ ผมเอามาจากเว็บอื่น ซึ่ง เพิ่งเห็นนี่แหละว่าเค้าปล่อยโดเมนหมดอายุ (อ่าว ชิบหอย)
http://www.ssckp.org/information-technology-for-crewphra-news/79-temples-tumbons-districts-amphures-77-provinces-database

ยุ่งเลย สรุป ตอนนี้เลยไม่มีต้นฉบับของ geodb ครับ น่าจะต้องแก้จาก ``geodb.json`` เอาแทน ซึ่งน่าจะต้องทำ tools ขึ้นมาใหม่ เพื่ออัพเดตข้อมูลลง ``geodb.json`` นะครับ ส่วน ``db.json`` น่าจะยังใช้ tools เดิมแก้ได้

ส่วนเรื่อง tools ต่างๆ ลองดูรายละเอียดจาก PR ดังต่อไปนี้นะครับ https://github.com/earthchie/jquery.Thailand.js/pull/2 https://github.com/earthchie/jquery.Thailand.js/pull/5 https://github.com/earthchie/jquery.Thailand.js/pull/7

โดย tools นี่ใช้ไฟล์ตั้งต้นเป็น json นะครับ ฉะนั้นถ้าจะตั้งต้นจาก Excel ท่านต้องทำ tools เพิ่มเช่นกัน ผมว่า แก้จาก json เลยง่ายดี

จริงๆ ว่าช่วงหยุดปีใหม่จะมารื้อทำ v2 อยู่ครับ ซึ่งมีแผนทำ tools ใหม่รวมอยู่ด้วย ถ้าไม่รอได้แนะนำรอ v2 ก่อนดีกว่าครับ

**Comment by earthchie** [comment]
ขออภัยที่ล่าช้าครับ

อัพเดตแล้ว https://github.com/earthchie/jquery.Thailand.js/commit/2bb64ff81ef12fa9917276531a9c3076ba58ebdb

details:
- ปรับปรุงรหัสไปรษณีย์ อ.แก่งหางแมว จ. จันทบุรี เป็น 22160
- ปรับปรุงรหัสไปรษณีย์ อ.วังเจ้า จ.ตาก เป็น 63180
- ปรับปรุงรหัสไปรษณีย์ อ.บางเสาธง จ.สมุทรปราการ เป็น 10570
- ย้าย ต.ท่าแฝก จ.อุตรดิษฐ์ ออกจากอ.ท่าปลา ไปอยู่ อ.น้ำปาด

เครื่องมือ build ฐานข้อมูล ทำเป็นเว็บไว้แล้วครับ 
https://earthchie.github.io/jquery.Thailand.js/jquery.Thailand.js/database/tools/index.html

**Comment by joezine** [comment]
ฝากแปะไว้ก่อน ยังไม่ได้ลองใช้ Tool

ต.เนินพระ อ.เมือง จ.ระยอง มีรหัสไปรษณีย์ทั้ง 21000 และ 21150

http://www.noplink.com/postcode_pv.php?p=%E0%B8%A3%E0%B8%B0%E0%B8%A2%E0%B8%AD%E0%B8%87

**Comment by earthchie** [comment]
แก้ไขแล้วครับ ขอบคุณครับ https://github.com/earthchie/jquery.Thailand.js/commit/49dde0a4e0da753d9f6fea4dff41f44b8c67addd

**Comment by joezine** [comment]
แปะอีกทีครับ


แขวงคลองกุ่ม เขตบึงกุ่ม มี 2 รหัสไปรษณีย์

10230 กับ 10240


http://www.noplink.com/postcode_a.php?a=%E0%B8%9A%E0%B8%B6%E0%B8%87%E0%B8%81%E0%B8%B8%E0%B9%88%E0%B8%A1&p=%E0%B8%81%E0%B8%A3%E0%B8%B8%E0%B8%87%E0%B9%80%E0%B8%97%E0%B8%9E%E0%B8%A1%E0%B8%AB%E0%B8%B2%E0%B8%99%E0%B8%84%E0%B8%A3

**Comment by joezine** [comment]
เพิ่มเติม


แขวงอ่าวนาง เขตเมืองจังหวัดกระบี่ เป็นรหัสไปรษณีย์ 81000

http://www.noplink.com/postcode_pv.php?p=%E0%B8%81%E0%B8%A3%E0%B8%B0%E0%B8%9A%E0%B8%B5%E0%B9%88

**Comment by earthchie** [comment]
รับทราบครับ เดี๋ยวหาเวลาแก้ให้ ยังไงคราวหน้ารบกวนเปิด issue ใหม่ให้หน่อยนะครับจะได้ติดตามได้สะดวก issue นี้มันปิดไปแล้ว มาแจ้งตรงนี้จะตกหล่นง่ายครับ

**Comment by earthchie** [comment]
ดำเนินการอัพเดตแล้วในเวอร์ชัน 1.5.3.3 ครับ ขอบคุณครับ

https://github.com/earthchie/jquery.Thailand.js/commit/cc93cf383121a19efec96be579c1fd784fa7c45c
