### ISSUE TITLE
ต.หนองเข็ง เปลี่ยนชื่อ ต.โนนสว่าง ภายใต้อ.เมืองบึงกาฬ ใน จ.บึงกาฬ

### ISSUE THREAD

**Issue by Supot** [earthchie/jquery.Thailand.js#24]
สวัสดีครับ
พอดีผมได้นำ plugin ตัวนี้ไปใช้งานกับระบบที่พัฒนาขึ้น เนื่องจากผมต้องใช้ รหัสจังหวัด, รหัสอำเภอ, รหัสตำบล ด้วย แต่ตัว database geodb.json ในจังหวัด บึงกาฬ ไม่มีข้อมูลส่วนนี้ผมเลยต้องแก้ไขไฟล์ raw_database.json เพื่อใช้งานเอง ทำให้พบว่า ต.หนองเข็ง ได้เปลี่ยนชื่อ ต.โนนสว่าง แล้วตั้งแต่อยู่ภายใต้จังหวัดเดิม (หนองคาย) ผมพยายามหาข้อมูลมายืนยันความถูกต้อง เท่าที่เจอคือ
https://th.wikipedia.org/wiki/%E0%B8%AD%E0%B8%B3%E0%B9%80%E0%B8%A0%E0%B8%AD%E0%B9%80%E0%B8%A1%E0%B8%B7%E0%B8%AD%E0%B8%87%E0%B8%9A%E0%B8%B6%E0%B8%87%E0%B8%81%E0%B8%B2%E0%B8%AC 
และ 
http://www.ratchakitcha.soc.go.th/DATA/PDF/2554/D/084/2.PDF
เลยแจ้งมาเผื่อทีมงานจะได้แก้ไขครับ

**Comment by earthchie** [comment]
ดำเนินการอัพเดตแล้วในเวอร์ชัน 1.5.3.3 ครับ ขอบคุณครับ

https://github.com/earthchie/jquery.Thailand.js/commit/cc93cf383121a19efec96be579c1fd784fa7c45c
