### ISSUE TITLE
แก้ไข JQL loop array ใน Magento ได้ element เกิน

### ISSUE THREAD

**Issue by leekung** [earthchie/jquery.Thailand.js#25]
เจอปัญหาที่ตัว JQL นะครับ เวลา loop ด้วย for(var i in this.buffer) ใน Magento
เนื่องจาก this.buffer มันเป็น array (หรือ object) ทำให้ได้ prototype ของ object มาด้วย เกิน length ของ this.buffer

ตัวอย่าง ลองรันใน browser console - Magento เช่นเว็บ https://www.sysinfo.co.th/
var buffer = [123], obj = []; for (var i in buffer) obj.push(buffer[i]); console.log(obj);

มันควรได้ 1 element เท่านั้น แต่มันได้ 34
ไม่รู้ระบบมันไปแก้อะไรกับ array
https://grmark-gmail.tinytake.com/sf/MjU2MjMxN183NzA3OTI0

ผลคือได้ result เกิน เกิด undefined ใน hint
https://grmark-gmail.tinytake.com/sf/MjU2MjMzMF83NzA3OTYx

ให้แก้ไขการ loop ด้วย
for (var i=0; i<this.buffer.length; i++) แทนครับ

function this.fetch
```
             for (var i in this.buffer) {
                 obj[i] = {};
                 for (const j in this.options) {
                     const field = this.options[j];
                     if (this.buffer[i][field]) {
                         obj[i][field] = this.buffer[i][field];
                     }
                 }
             }
```
แก้เป็น
```
             for (var i=0; i<this.buffer.length; i++) {
                 obj[i] = {};
                 for (const j in this.options) {
                     const field = this.options[j];
                     if (this.buffer[i][field]) {
                         obj[i][field] = this.buffer[i][field];
                     }
                 }
             }
```

function this.orderBy
#จุดที่ 1
```
         // prepare object
         const obj = [];
         for (var i in this.buffer) {
             obj.push([i, this.buffer[i][field]]);
         }
```

แก้เป็น

```
         // prepare object
         const obj = [];
         for (var i=0; i<this.buffer.length; i++) {
             obj.push([i, this.buffer[i][field]]);
         }
```

#จุดที่ 2 
```
         results = [];
         for (var i in obj) {
             results.push(this.buffer[obj[i][0]]);
         }
```

แก้เป็น
```
         results = [];
         for (var i=0;i<obj.length; i++) {
             results.push(this.buffer[obj[i][0]]);
         }
```

ขอบคุณครับ

**Comment by earthchie** [comment]
รบกวนทำเป็น Pull Request มาให้หน่อยครับ จะได้ขึ้นเครดิต

ขอบคุณครับ

**Comment by leekung** [comment]
ต้องไปแก้ที่ repo ของ JQL หรือเปล่าครับ

**Comment by earthchie** [comment]
ใช่คร้าบ รบกวนด้วย
