### ISSUE TITLE
Database Tools raw_database.json ที่เป็นภาษาอังกฤษ

### ISSUE THREAD

**Issue by blxssom** [earthchie/jquery.Thailand.js#27]
คือลองแก้จาก raw_database.json ไฟล์เดิมที่มีข้อมูลเป็นภาษาไทย ให้เป็นภาษาอังกฤษ
แล้วนำมาบีบอัดลงโดยใช้ database tool คือไม่สามารถบีบอัดไฟล์ได้หรอคะ?

**Comment by earthchie** [comment]
ยังไม่รองรับเนื่องจากตัวบีบอัดเป็นการรวมคำซ้ำภาษาไทยเค้าด้วยกันครับ (dictionary compress)

ยังไง ตอนนี้เดี๋ยวขอปิดประเด็นนี้ก่อน ไปคุยต่อใน https://github.com/earthchie/jquery.Thailand.js/issues/26 นะครับ
