### ISSUE TITLE
พบว่า typeahead ไม่พัฒนาต่อมาหลายปีแล้ว

### ISSUE THREAD

**Issue by Chayes2017** [earthchie/jquery.Thailand.js#28]
typeahead ไม่พัฒนาต่อหลายปีแล้ว ถ้าเป็นไปได้ อยากให้ใช้ lib auto complete ตัวอื่นแทนที่ยังมีคนพัฒนาต่ออยู่ครับ  เช่น Select2  เป็นต้นครับ

reference
https://github.com/twitter/typeahead.js/tree/integration-0.11.2

**Comment by earthchie** [comment]
1. Select2 ไม่ใช่ autocomplete แต่เป็นการ search จาก options ซึ่งต้องมีการสร้างตำบลที่มีทั้งหมดยัดลงไปเลย ทำให้ performance แย่มาก ไม่เหมาะกับงานนี้ครับ

2. ตอนนี้ typeahead ยังไม่มีปัญหา คงจะอยู่กับมันต่ออีกสักพักครับ จริงๆ มีแผนจะรื้อใหม่ และทำเองทั้งหมดด้วย แต่งานยุ่งมากเลยยังไม่ว่างทำเลยครับ
