### ISSUE TITLE
แก้รหัสไปรษณีย์เกาะเต่า

### ISSUE THREAD

**Issue by iampz** [earthchie/jquery.Thailand.js#29]
รหัสไปรษณีย์ของเกาะเต่าในฐานข้อมูลตอนนี้ระบุเป็น 84280 ซึ่งไม่ถูกต้อง ที่ควรเป็นคือ 84360 ครับ

**Comment by iampz** [comment]
และตำบลฉลอง และ ตำบลราไวย์ อำเภอเมืองภูเก็ต รหัสไปรษณีย์จะต้องเป็น 83130 ครับ

**Comment by iampz** [comment]
ต.โคกโม่ง อ.คลองหอยโข่ง เฉพาะส่วน "บ้านพักกองบิน 56" รหัสไปรษณีย์จะเป็น 90115 ตอนนี้มันขึ้นแค่ 90230 เท่านั้นครับ

**Comment by earthchie** [comment]
ในกรณีที่ผิด รบกวนขออ้างอิงด้วยได้ไหมครับ เพราะกรณีที่ผิดนั้นจะแตกต่างจากกรณีที่เพิ่มใหม่ตรงที่ 

ผิด = ถอดของเก่าออก เปลี่ยนเป็นของใหม่
เพิ่มใหม่ = ของเก่าเก็บไว้ ของใหม่ก็เพิ่มเข้าไป

เช่น 

เกาะเต่ามีการใช้งานรหัสไปรษณีย์ 84280 อยู่เยอะพอสมควร
![image](https://user-images.githubusercontent.com/7013039/45921083-b1342c80-bed8-11e8-9968-5465837fec5f.png)
http://www.holidaythai.com/Thailand-Hotels-City-80.htm

ตำบลราไวย์ใน Google เป็น 83100
![image](https://user-images.githubusercontent.com/7013039/45921135-e7be7700-bed9-11e8-963e-54d2e3e3807c.png)

ในขณะที่ตำบลฉลองเป็น 83130 ตามที่แจ้งมาจริงครับ จึงสงสัยว่าเป็นไปได้หรือไม่ที่ราไวย์มีการใช้งานทั้งสองรหัสปณ.
![image](https://user-images.githubusercontent.com/7013039/45921145-2eac6c80-beda-11e8-9b4f-8d3a31bca845.png)

--
แต่ในเบื้องต้นผมเลยจะใช้มาตรการ "เพิ่มใหม่" ให้ก่อนครับ ไม่เอาของเดิมออก

**Comment by earthchie** [comment]
ดำเนินการเรียบร้อยครับ https://github.com/earthchie/jquery.Thailand.js/commit/808d5e143a8fe3ae9339bd1d54a28b7b044b93e2

ถ้ามีเพิ่มเติม re-open ได้เลยนะครับ

**Comment by iampz** [comment]
เห็นด้วยกับการไม่ลบแล้วใช้วิธีเพิ่มไปเพราะอาจเป็นไปได้เรื่องพื้นที่เดียวกันใช้หลายรหัสไปรษณีย์ครับ ส่วนเรื่องอ้างอิงนี่ต้องขออภัยด้วยที่ไม่สามารถหาอ้างอิงที่น่าเชื่อถือได้ (อย่างที่น่าจะทราบกันอยู่แล้ว แม้แต่ open data ใน data.go.th ยังไม่มีข้อมูลส่วนนี้ให้เลย) โดยปกติผมจะเช็คข้อมูลหลายๆ ส่วนประกอบกันแล้วค่อยประเมินว่าควรจะเป็นเลขไหนครับ

ยกตัวอย่าง ข้อมูลอ้างอิงที่ผมใช้ เช่น

1. เกาะเต่า
http://www.kohtao.go.th/office.php
http://noplink.com/postcode_p.php?p=84280
http://noplink.com/postcode_p.php?p=84360

2. ราไวย์และฉลอง
http://www.rawai.go.th/index.php
http://phuketchalong.go.th/public/
http://www.noplink.com/postcode_p.php?p=83100
http://www.noplink.com/postcode_p.php?p=83130

หมายเหตุ 1: ผมมักจะ search หาด้วย keyword "สำนักงานเทศบาลตำบลxxx" เพราะคิดว่าข้อมูลของหน่วยงานภาครัฐน่าจะแม่นยำกว่าของเอกชนครับ (ซึ่งความเชื่อนี้ก็อาจไม่จริงเสมอไปก็ได้) และบางครั้งถ้ายังไม่แน่ใจอาจลองหาที่อยู่หน่วยงานรัฐอื่นใน google เพิ่อเช็คความถูกต้องอีกรอบเช่นกรณี ต.ฉลอง ผมหาของสวนพฤกษชาติภูเก็ตเพิ่มได้ข้อมูลตามนี้

![image](https://user-images.githubusercontent.com/523813/45925450-afea1a80-bf3f-11e8-8ec5-b2028d716549.png)

หมายเหตุ 2: ที่ผมยอมรับการอ้างอิงจากเว็บ noplink เนื่องจากผมใช้อ้างอิงมาตลอดไม่น่าจะต่ำกว่าสามปี (ผมขายของออนไลน์ส่งของวันละ 50-100 ออเดอร์ต่อวัน) แล้วพบว่าเว็บนี้ค่อนข้างถูกต้อง แต่อาจจะมีข้อมูลใหม่บางพื้นที่ที่ไม่ได้อัพเดทตาม เช่น 10230, 10240 โดยใน noplink เขตบึงกุ่มยังไม่ได้แยกแขวงนวมินทร์และนวลจันทร์ออกมาตามประกาศผู้ว่าก.ท.ม.ปี 2552 อะไรประมาณนี้ครับ
http://noplink.com/postcode_p.php?p=10230
http://noplink.com/postcode_p.php?p=10240
https://th.wikipedia.org/wiki/%E0%B9%80%E0%B8%82%E0%B8%95%E0%B8%9A%E0%B8%B6%E0%B8%87%E0%B8%81%E0%B8%B8%E0%B9%88%E0%B8%A1

คิดว่าคงมีแก้ไขเพิ่มเติมอีกเรื่อยๆ ตามที่พบ ถ้าเจออีกยังไงจะ re-open เพื่อแจ้งไปครับ

**Comment by earthchie** [comment]
ขอบพระคุณที่ช่วยกันปรับปรุงข้อมูลครับ

**Comment by iampz** [comment]
ต.พยอม (อ.วังน้อย จ.พระนครศรีอยุธยา) เฉพาะหมู่ 5 ใช้รหัสไปรษณีย์ 13180 ครับ อันนี้ลูกค้ายืนยันมาตามนี้ และในเว็บ noplink แจ้งไว้เช่นเดียวกับที่ลูกค้าแจ้งมาครับ

http://www.noplink.com/postcode_t.php?t=%E0%B8%9E%E0%B8%A2%E0%B8%AD%E0%B8%A1&a=%E0%B8%A7%E0%B8%B1%E0%B8%87%E0%B8%99%E0%B9%89%E0%B8%AD%E0%B8%A2&p=%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B8%99%E0%B8%84%E0%B8%A3%E0%B8%A8%E0%B8%A3%E0%B8%B5%E0%B8%AD%E0%B8%A2%E0%B8%B8%E0%B8%98%E0%B8%A2%E0%B8%B2&pc=13170&cm=%5C%22%E0%B8%97%E0%B8%B1%E0%B9%89%E0%B8%87%E0%B8%95%E0%B8%B3%E0%B8%9A%E0%B8%A5%28%E0%B8%A2%E0%B8%81%E0%B9%80%E0%B8%A7%E0%B9%89%E0%B8%99+%E0%B8%AB%E0%B8%A1%E0%B8%B9%E0%B9%88+5+%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B8%A3%E0%B8%AB%E0%B8%B1%E0%B8%AA+13180%29%5C%22

น่าจะต้องเพิ่มรหัสไปรษณีย์ 13180 สำหรับต.พยอมครับ

หมายเหตุ: เห็นว่า 13180 มีใช้กับ ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี ในเว็บ noplink ด้วยแต่ในระบบไม่มี ซึ่งอันนี้ผมไม่แน่ใจนะครับ ไม่ได้เช็คเพิ่มสำหรับพื้นที่นี้
