### ISSUE TITLE
กรอกใน DEMO ไม่ได้

### ISSUE THREAD

**Issue by kamontat** [earthchie/jquery.Thailand.js#3]
ใช้ `Safari` พอกดไปที่ input แล้วมันก็เด้ง conbobox มาแปปหนึ่งแล้วก็หายไป พร้อมกับ unfocus ให้ด้วย เลยไม่สามารถกรอกข้อมูลได้เลย 

ไม่แน่ใจว่าดู video ได้ไหม
[VDO](https://streamable.com/iuv0x)

**Comment by earthchie** [comment]
แก้แล้วครับ แม่งเป็นบัคของ Typeahead.js
https://github.com/twitter/typeahead.js/issues/1526
