### ISSUE TITLE
Autocomplete ยาวจนล้นหน้าจอ

### ISSUE THREAD

**Issue by gluons** [earthchie/jquery.Thailand.js#33]
Autocomplete ยาวจนล้นหน้าจอตามภาพเลยครับ

![default](https://user-images.githubusercontent.com/4688092/46905784-9b87b500-cf22-11e8-8ea0-6498059c60ab.png)

**Comment by earthchie** [comment]
มี options ที่ใช้ลิมิตจำนวนให้เหลือตามจำนวนต้องการอยู่นะครับ

**Comment by gluons** [comment]
อ๋อ ครับ พอดีผมลองเล่นในเว็บ demo แล้วมันล้นครับ เลยมาแจ้ง
