### ISSUE TITLE
สอบถามครับ

### ISSUE THREAD

**Issue by Signature72** [earthchie/jquery.Thailand.js#35]
ถ้าผมอยากให้มี scroll bar ในส่วนของ เมนู ต้องทำอย่างไรครับ

#มือใหม่หัดเขียนครับ

**Comment by earthchie** [comment]
แก้ที่ css ครับ กำหนด max-height จากนั้นตั้ง overflow: auto ครับ

**Comment by Signature72** [comment]
ขอบคุณมากครับ 👍
