### ISSUE TITLE
ใช้กับ ruby on rails ได้ไหมครับ

### ISSUE THREAD

**Issue by kmtanapat** [earthchie/jquery.Thailand.js#36]
พอดี กำลังฝึกเขียน Ruby on Rails อยากทราบวิธีนำไปใช้ใน framework นี้ครับ

**Comment by earthchie** [comment]
อ่าน readme ได้เลยครับ lib นี้ทำงานฝั่ง client ฉะนั้นไม่มีประเด็นเรื่องว่า server เขียนด้วยอะไรครับ

https://github.com/earthchie/jquery.Thailand.js/blob/master/README.md
