### ISSUE TITLE
การใช้งานมากกว่า 1 ฟอร์มขึ้นไป

### ISSUE THREAD

**Issue by NantipatSoftEn** [earthchie/jquery.Thailand.js#37]
ขอคำแนะนำในการใช้งานแบบ 1 ฟอร์มขึ้นไปครับเนื่องจากผมพบปัญหาชื่อตัวแปรซ้ำแล้วไม่ Auto Complete ให้
`
$.Thailand({ 
    database: './jquery.Thailand.js/database/db.json', 
    $district: $('#district'),
    $amphoe: $('#amphoe'),
    $province: $('#province'),
    $zipcode: $('#zipcode'), 

   $district: $('#district2'),
    $amphoe: $('#amphoe2'),
    $province: $('#province2'),
    $zipcode: $('#zipcode2'), 
});
`

**Comment by earthchie** [comment]
แบบนี้ครับ

```javascript
$.Thailand({
   database: './jquery.Thailand.js/database/db.json',
   $district: $('#district'),
   $amphoe: $('#amphoe'),
   $province: $('#province'),
   $zipcode: $('#zipcode'),
});

$.Thailand({
   database: './jquery.Thailand.js/database/db.json',
   $district: $('#district2'),
   $amphoe: $('#amphoe2'),
   $province: $('#province2'),
   $zipcode: $('#zipcode2'),
});
```
