### ISSUE TITLE
ในตัว input มันเราไม่สามารถเคลียร์ค่า value ได้หรอคับเวลา onfocus

### ISSUE THREAD

**Issue by tonspu55** [earthchie/jquery.Thailand.js#39]
ผมลองแล้วค่ามันไม่หายไปเลยครับ สมมุติเราเลือกเขตจุตจักรไปแล้วอยากเคลียร์ค่ามันทิ้งด้วยการ focus ที่ textbox แต่ค่ามันก็ไม่หายไปเลยครับผม

**Comment by earthchie** [comment]
เนื่องจากเราใช้ Twitter typeahead เลยไม่สามารถเคลียร์ค่าด้วยวิธีปกติได้ครับผม

ต้องทำแบบนี้ครับ
```javascript
$(input).typeahead('value', '');
```

ตัวอย่างครับ https://jsfiddle.net/earthchie/g4orLb3f/

![image](https://user-images.githubusercontent.com/7013039/52983100-0474c180-341c-11e9-8878-320171497d61.png)

**Comment by tonspu55** [comment]
@earthchie ขอบคุณมากครับ clear value ได้ง่ายเลยครับ
