### ISSUE TITLE
อยากให้เพิ่ม code ของจังหวัดด้วยครับ

### ISSUE THREAD

**Issue by PNNutkung** [earthchie/jquery.Thailand.js#4]
ขอบคุณมากครับสำหรับ project นี้ มีประโยชน์เวลากรอกที่อยู่บ้านมากครับ
ผมอยากให้มี code ของจังหวัดเพิ่มเข้ามาครับ จะง่ายต่อการใช้ geometric query มากครับ
อย่างเช่น

| รหัสตำบล | ชื่อตำบล |
|:---:|:---|
|100101	|พระบรมมหาราชวัง|
|100102	|วังบูรพาภิรมย์|   
|100103|	วัดราชบพิธ   |
|100104|	สำราญราษฎร์   |
|100105|	ศาลเจ้าพ่อเสือ   |
|100106|	เสาชิงช้า   |
|100107|	บวรนิเวศ   |

| รหัสอำเภอ| ชื่ออำเภอ | 
|:---:|:---|
| 1001 | เขตพระนคร   |
| 1002 | เขตดุสิต   |
| 1003 | เขตหนองจอก   |
| 1004 | เขตบางรัก|

| รหัสจังหวัด | จังหวัด |
|:---:|:---|
|10	|กรุงเทพมหานคร   |
|11	|สมุทรปราการ   |

ขอบคุณครับ

**Comment by earthchie** [comment]
รบกวนยกตัวอย่างการนำไปประยุกต์ให้หน่อยได้ไหมครับ พอดีผมไม่มีความรู้ด้าน geometric query เลยไม่แน่ใจว่ามันนอก scope แล้วหรือไม่ ถ้ายังอยู่ใน scope จะพิจารณาเพิ่มฟีเจอร์ให้ครับ

อย่างไรก็ตาม ผมมีฐานข้อมูลให้ครับ ตัวนี้เป็นต้นฉบับของฐานข้อมูลที่ใช้ในโปรเจคนี้
สามารถนำไปดัดแปลงได้เลยครับ
https://docs.google.com/spreadsheets/d/1BNu_ofhdyyuyD8g9iVMZlohcyTH5qNBXtQj3HD3BqLY/edit?usp=sharing

**Comment by PNNutkung** [comment]
สมมติผมทำเว็บทำแบบสอบถาม คนที่ทำแบบสอบถามนี้ต้องลงไปในพื้นที่จริงๆ จะต้องระบุว่ากรอกที่ตำบลไหน จังหวัดไหน อำเภอไหน 
เวลาตอนที่เราจะมาดูบน map เราสามารถรู้ขอบเขตเฉพาะของจังหวัด, อำเภอ, หรือ ตำบลได้ครับ

**Comment by earthchie** [comment]
ผมเพิ่งพบว่าฐานข้อมูลที่ผมมี มันไม่ใช่รหัสที่เป็นสากล แต่เป็นรหัสที่ใช้กันภายในไปรษณีย์เท่านั้น ใช้กับเคสนี้ไม่ได้
ถ้าคุณ @PNNutkung มีข้อมูลรบกวนส่งมาให้หน่อย หรือจะทำ PR มาเลยก็ได้ครับ

**Comment by PNNutkung** [comment]
ผมมีแบบนี้ครับ เดี๋ยวจะช่วยกรอกนะครับ
[thailand_db.zip](https://github.com/earthchie/jquery.Thailand.js/files/907714/thailand_db.zip)

**Comment by earthchie** [comment]
ช่วงนี้ข้อมูลถูก optimize เรื่อยๆ จนโครงสร้างข้อมูลชักไม่เอื้อต่อการผูก id ลงไปแล้ว ล่าสุดมีการยุบคำซ้ำด้วย (แต่ไอดีมันไม่ซ้ำไง) ผมไม่ค่อยเชี่ยวเรื่องการออกแบบ data structure ซะด้วย ขอติดไว้ก่อน รอท่านอื่นๆ optimize กันจนนิ่งแล้วจะมาเพิ่มให้นะครับ

**Comment by PNNutkung** [comment]
จากของพี่ @dtinth 
```
[ [ 'กระบี่',
    [ [ 'คลองท่อม',
        [ [ 'คลองท่อมเหนือ', [ 81120 ] ],
          [ 'คลองท่อมใต้', [ 81120 ] ],
          [ 'คลองพน', [ 81170 ] ],
          [ 'ทรายขาว', [ 81170 ] ],
          [ 'พรุดินนา', [ 81120 ] ],
          [ 'ห้วยน้ำขาว', [ 81120 ] ],
          [ 'เพหลา', [ 81120 ] ] ] ],
      [ 'ปลายพระยา',
        [ [ 'คีรีวง', [ 81160 ] ],
          [ 'ปลายพระยา', [ 81160 ] ],
          [ 'เขาต่อ', [ 81160 ] ],
          [ 'เขาเขน', [ 81160 ] ] ] ],
      …
```

ผมว่าน่าจะเพิ่มเข้าไปแบบนี้ได้นะครับ
```
[ [ 'กระบี่', 81,
    [ [ 'คลองท่อม', 8104,
        [ [ 'คลองท่อมเหนือ', 810402, [ 81120 ] ],
          [ 'คลองท่อมใต้', 810401, [ 81120 ] ],
          [ 'คลองพน', 810403, [ 81170 ] ],
          [ 'ทรายขาว', 810404, [ 81170 ] ],
          [ 'พรุดินนา', 810406, [ 81120 ] ],
          [ 'ห้วยน้ำขาว', 810405, [ 81120 ] ],
          [ 'เพหลา', 810407, [ 81120 ] ] ] ],
      [ 'ปลายพระยา', 8106,
        [ [ 'คีรีวง', 810604, [ 81160 ] ],
          [ 'ปลายพระยา', 810601, [ 81160 ] ],
          [ 'เขาต่อ', 810603, [ 81160 ] ],
          [ 'เขาเขน', 810602, [ 81160 ] ] ] ],
      …
```
 
แต่ผมยังไม่รู้ว่าแบบนี้ดีที่สุดรึเปล่านะครับ

**Comment by earthchie** [comment]
@PNNutkung ตอนนี้ผมทำข้อมูลเสร็จแล้ว ต้องการเอา code ของพื้นที่ต่างๆ ไปพล็อตแผนที่ดูว่าถูกต้องไหม (จะสุ่มตรวจ) ไม่ทราบต้องทำอย่างไรชี้แนะหน่อยครับ ไม่รู้จะค้นด้วย keyword อะไร หาไม่เจอเลย

**Comment by earthchie** [comment]
ผมยังไม่ได้อัพเดตเอกสาร แต่โค้ดเอาขึ้นแล้ว เวอร์ชัน 1.5.0 เป็นต้นไปนะครับ

ให้เลือกใช้ฐานข้อมูล geodb.json หรือ geodb.zip ครับ 
db ปกติ ไม่มี area code เพื่อให้ไฟล์เล็ก เพราะไม่น่าได้ใช้กันบ่อยๆ ผมเลยจับแยกดีกว่า

ตัวอย่างวิธีใช้งานครับ เทสแล้วใช้ได้ไม่ได้รบกวนแจ้งด้วยนะครับ

```html
<input type="text" id="search">
<input type="text" id="district_code">
<input type="text" id="amphoe_code">
<input type="text" id="province_code">
```

```javascript
$.Thailand({
            database: './jquery.Thailand.js/database/geodb.json', 

            $search: $('#search'),
            $district_code: $('#district_code'),
            $amphoe_code: $('#amphoe_code'),
            $province_code: $('#province_code'),

            onDataFill: function(data){
                console.log(data);
            }
});
```
