### ISSUE TITLE
สอบถามเกี่ยวกับการติดตั้งใช้งานครับ

### ISSUE THREAD

**Issue by vira492010** [earthchie/jquery.Thailand.js#40]
ผมสอบถามเกี่ยวกับการติดตั้งใช้งานหน่อยครับ ผมดาวน์โหลด ตัวโปรเจค จาก github โดยติดตั้งที่เครื่องจำลอง web โดยยังไม่ได้เปลี่ยนแปลงโค้ดใด ๆ รันผ่าน google chrome ระบบให้รอโหลดฐานข้อมูลดังภาพ ครับ ช่วยแนะนำ วิธีแก้ไข หรือวิธีติดตั้งที่ถูกต้องหน่อยครับ

![image](https://user-images.githubusercontent.com/49437297/55794239-f45d9200-5aee-11e9-8c90-c2267e6e09aa.png)

**Comment by earthchie** [comment]
ขอดู error message ใน console หน่อยครับ

**Comment by vira492010** [comment]
![image](https://user-images.githubusercontent.com/49437297/55857685-f7f92380-5b97-11e9-95c7-b41b09b509b3.png)

**Comment by vira492010** [comment]
error message ใน console  ถูกต้องไหมครับ

**Comment by earthchie** [comment]
มันหาฐานข้อมูลไม่เจอครับ 

มีทางแก้สองทาง
1. เช็ค path ในถูก
2. เอาฐานข้อมูลไปวางให้ตรง

**Comment by vira492010** [comment]
ผมวางถูก path ไหมครับ 
![image](https://user-images.githubusercontent.com/49437297/55858073-ecf2c300-5b98-11e9-925e-9379a06797d6.png)
