### ISSUE TITLE
ฐานข้อมูลจาก Kerry Express ครับ

### ISSUE THREAD

**Issue by clonezer** [earthchie/jquery.Thailand.js#42]
![Screen Shot 2019-05-16 at 4 11 35 PM](https://user-images.githubusercontent.com/582587/57841848-885d0080-77f5-11e9-9592-64267f804c75.png)

พอดีผมใช้งานเว็บไซต์ของ kerry express ที่เอาไว้ให้ลูกค้าสร้างใบปะหน้าก่อนที่จะเอาไปส่งที่สาขาแล้วผมก็เจอว่า เขามีการเรียก data ของตำบลมาทั้งหมดตอนแสดง suggestion บน textfield จาก url นี้ครับ
[https://cms.th.kerryexpress.com/easyship/resources/subdistrict.json](https://cms.th.kerryexpress.com/easyship/resources/subdistrict.json)
คิดว่าน่าจะมีประโยชน์ในการ recheck หรือ update ฐานข้อมูลเพิ่มเติมครับ

**Comment by earthchie** [comment]
ผมเช็คแล้วของที่เราช่วยกันทำล่าสุดมากกว่าครับ ยกตัวอย่างเช่น บางเสาธงเปลี่ยนจาก 10540 เป็น 10570 แล้ว
