### ISSUE TITLE
เพิ่มรหัสไปรษณีย์ ต.ห้วยกะปิ จ.ชลบุรี

### ISSUE THREAD

**Issue by seksan470029** [earthchie/jquery.Thailand.js#43]
ต.ห้วยกะปิ จ.ชลบุรี รหัสไปรษณีย์ มี 2 เลขครับ คือ 20000 (มีอยู่แล้ว)  และ 20130 (เพิ่มเติม)

{
        "district": "ห้วยกะปิ",
        "amphoe": "เมืองชลบุรี",
        "province": "ชลบุรี",
        "zipcode": 20130,
        "district_code": 200115,
        "amphoe_code": 2001,
        "province_code": 20
    },

**Comment by earthchie** [comment]
เรียบร้อยครับ
