### ISSUE TITLE
ช่วยหาวิธี Update แหล่งข้อมูลจาก Opendata ด้วยครับ

### ISSUE THREAD

**Issue by songwutk** [earthchie/jquery.Thailand.js#46]
ข้อมูลพิกัด LAT/LONG ที่บ่งชี้ชื่อตำบล อำเภอ จังหวัด 

https://data.go.th/dataset/item_c6d42e1b-3219-47e1-b6b7-dfe914f27910

**Comment by earthchie** [comment]
เอา raw_database ไป map แล้วโยนไป compress ที่ https://earthchie.github.io/jquery.Thailand.js/jquery.Thailand.js/database/tools/
