### ISSUE TITLE
Spelling of Arun Ammarin

### ISSUE THREAD

**Issue by kimfucious** [earthchie/jquery.Thailand.js#47]
Is Arun Ammarin อรุณอัมรินทร์ or บางกอกน้อย?

Wikipedia says the latter, but I'd trust a Kohn Thai more 😉

**Comment by earthchie** [comment]
Arun Ammarin is "อรุณอมรินทร์".

Arun Ammarin is "แขวง", a sub district, while Bangkok Noi is "เขต", a district.

Bangkok Noi is "เขต", a district, while Arun Ammarin is "แขวง", a sub district, located at the north of Bangkok Noi

![Screenshot_20200703_223135_com google android apps maps](https://user-images.githubusercontent.com/7013039/86483000-4f774680-bd7d-11ea-8cd8-358a3508c5da.jpg)

**Comment by kimfucious** [comment]
Thanks for the clarification!
