### ISSUE TITLE
แยกแขวงบางนาออกเป็น บางนาเหนือ และ บางนาใต้

### ISSUE THREAD

**Issue by iampz** [earthchie/jquery.Thailand.js#48]
26 กรกฎาคม พ.ศ. 2560 แขวงบางนาเดิมในเขตบางนาได้แยกแขวงออกเป็น บางนาเหนือ และ บางนาใต้ แต่ในฐานข้อมูลยังมีแค่แขวงบางนาอย่างเดียวอยู่ รบกวนอัพเดทด้วยนะครับ ขอบคุณครับ

https://th.wikipedia.org/wiki/%E0%B9%80%E0%B8%82%E0%B8%95%E0%B8%9A%E0%B8%B2%E0%B8%87%E0%B8%99%E0%B8%B2

**Comment by earthchie** [comment]
เรียบร้อยครับ
