### ISSUE TITLE
ผมต้องการแสดงค่า response

### ISSUE THREAD

**Issue by nobutsta** [earthchie/jquery.Thailand.js#9]
โปรแกรมทำงานได้เร็วมากครับ ดีกว่า ajax ที่ผมใช้อยู่หลายปีแล้วหลายวินาที แต่ผมอยากปรับการแสดงผลหน่อยครับ ในฟังก์ชัน oncomplete ผมอยากให้แสดงผลว่ามันส่งอะไรมา โดยผมเขียนอย่างนี้แต่มันไม่ขึ้น ต้องทำอย่างไรครับ

```
            onComplete: function(data){
		console.log(data)
            }
```

**Comment by earthchie** [comment]
มันเป็น callback เพื่อบอกว่า initial เรียบร้อยแล้วน่ะครับ (เนื่องจากฐานข้อมูลโหลดแบบ async)

รบกวนอธิบายหน่อยครับว่า ตอนนี้ต้องการทำอะไร แล้วต้องการค่าอะไรครับ

**Comment by nobutsta** [comment]
คือผมจะทำให้ข้อมูลที่เลือกไปแสดงอยู่ในที่เดียวกันครับ เช่น พิมพ์ชื่อตำบล แล้วเลือกอันหนึ่ง แล้วข้อมูลที่เลือก (อำเภอ,จัวหวัด,รหัสปณ) ไปรวมแสดงอยู่ภายใน input ที่ใช้คนหานั้น หรือไม่ก็ใน span ที่สร้างไว้อีกอัน ซึ่งผมก็เลยอยากรู้ว่าค่า response มันส่งอะไรมาบ้าง

**Comment by earthchie** [comment]
รับทราบครับ เดี๋ยวผมเพิ่ม event ให้แต่ละฟิลด์ แยกกันเลยเพื่อความยืดหยุ่น

**Comment by earthchie** [comment]
[อัพเดต](https://github.com/earthchie/jquery.Thailand.js/commit/6fbc2dba93c3d34b71a9ec3290292628a1ca7dfa)เป็น version 1.3.0 แล้วครับ ดูรายละเอียดเพิ่มเติมได้จากโค้ดใน [Demo](https://github.com/earthchie/jquery.Thailand.js/blob/master/index.html)

**Comment by nobutsta** [comment]
ผมลองทดสอบกับ 1.3.0 แล้วปรากฏว่ามันไม่แสดงช่องให้กรอกข้อความ ตรวจสอบดูจาก console แล้วไม่ขึ้น error / class="demo" คืออะไรครับ

**Comment by earthchie** [comment]
ขอดู error messege เต็มๆ ครับ

**Comment by nobutsta** [comment]
https://www.thaircon.com/search.php

อันนี้คือเพจที่ใช้ทดสอบครับ ไม่มี error และใช้งานไม่ได้ครับ

**Comment by earthchie** [comment]
ไฟล์ jquery.Thailand.min.js ที่เรียกใช้ ยังเป็นเวอร์ชันเก่าอยู่ครับ ผมเห็นเป็น 1.2.0 อยู่เลย

- เช็คให้แน่ใจว่าอัพเดตเป็น 1.3.6 แล้ว
- เช็คดูว่าติดแคชไหม ทั้งแคชจากฝั่ง server และแคชจากฝั่ง cloudflare

https://www.thaircon.com/assets/js/jquery.Thailand.min.js
![image](https://cloud.githubusercontent.com/assets/7013039/25115282/50035156-242f-11e7-9fb3-61112199b0fd.png)

**Comment by nobutsta** [comment]
ได้แล้วครับ ผมไม่ได้อัพเดท .js เป็นเวอร์ชันล่าสุด ขอบคุณมากครับ
